# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: taotaomami's house
url: http://HuangTao123.github.io
feed: /atom.xml
author_info: <a href="http://HuangTao123.github.io/">taotaomami</a>

myblog:
  gavatar: images/2.jpg
  gpname: HuangTao
  github: https://github.com/HuangTao123
  email: mailto:409273584@qq.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
